export const SIGN_UP_REQUEST = 'SIGN_UP_REQUEST'; 
export const SIGN_UP_LOADING = 'SIGN_UP_LOADING';
export const SIGN_IN_REQUEST = 'SIGN_IN_REQUEST';
export const SIGN_IN_LOADING = 'SIGN_IN_LOADING';
export const FETCH_CURRENT_USER_INFO = 'FETCH_CURRENT_USER_INFO';
export const SET_CURRENT_USER_INFO = 'SET_CURRENT_USER_INFO';